/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package P2_Chess;

import javax.swing.JLayeredPane;



/**
 *
 * @author waldonavas
 */
public class Ajedrez extends javax.swing.JFrame
{

    /**
     * Creates new form Ajedrez
     */
    public static java.net.URL glow = Ajedrez.class.getResource("/P2_Chess/sprites/glow.png");
    public static java.net.URL selectedglow = Ajedrez.class.getResource("/P2_Chess/sprites/selectedglow.png");
    
    public Ajedrez()
    {
        initComponents();
        turn.setText("Empiezan las Piezas\nBlancas");
        layers.setLayer(tablero, JLayeredPane.DEFAULT_LAYER);
        Tablero.spawnPieces();
        
    }
    
    public static void cleanGlows()
    {
        int j = layers.getComponentCountInLayer(JLayeredPane.MODAL_LAYER);
        //System.out.println(j);
        for (int i = 0; i < j; i++)
        {
            layers.remove(layers.getComponentsInLayer(JLayeredPane.MODAL_LAYER)[0]);  
        }
        layers.repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        layers = new javax.swing.JLayeredPane();
        tablero = new javax.swing.JLabel();
        turn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajedréz");
        setMinimumSize(new java.awt.Dimension(850, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(null);

        layers.setPreferredSize(new java.awt.Dimension(620, 620));

        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/P2_Chess/sprites/board.png"))); // NOI18N
        tablero.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                tableroMousePressed(evt);
            }
        });
        layers.add(tablero);
        tablero.setBounds(5, 5, 600, 600);

        getContentPane().add(layers);
        layers.setBounds(10, 10, 620, 620);

        turn.setText("Atacan las Piezas Blancas\n");
        getContentPane().add(turn);
        turn.setBounds(650, 30, 180, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableroMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tableroMousePressed
    {//GEN-HEADEREND:event_tableroMousePressed
        cleanGlows();
        Tablero.isMoving = false;
    }//GEN-LAST:event_tableroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Ajedrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLayeredPane layers;
    public static javax.swing.JLabel tablero;
    public static javax.swing.JLabel turn;
    // End of variables declaration//GEN-END:variables
}
